### ISSUE TITLE
Create issues to implement design

### ISSUE THREAD

**Issue by bbodine1** [ideacrew/enroll-fe2#15]
This is not a code related issue.

This issue will be sued to create other issues that will be the pieces to create the entire Tax Calculator App.
```[tasklist]
### Tasks
- [ ] https://github.com/ideacrew/enroll-fe2/issues/11
- [ ] https://github.com/ideacrew/enroll-fe2/issues/10
- [ ] https://github.com/ideacrew/enroll-fe2/issues/12
- [ ] https://github.com/ideacrew/enroll-fe2/issues/13
- [ ] https://github.com/ideacrew/enroll-fe2/issues/17
- [x] Add route for FAQs view
- [ ] https://github.com/ideacrew/enroll-fe2/issues/19
```

```[tasklist]
### Add views and routes for each step
- [ ] https://github.com/ideacrew/enroll-fe2/issues/22
- [ ] https://github.com/ideacrew/enroll-fe2/issues/23
- [ ] https://github.com/ideacrew/enroll-fe2/issues/24
- [ ] https://github.com/ideacrew/enroll-fe2/issues/25
- [ ] https://github.com/ideacrew/enroll-fe2/issues/26
- [ ] https://github.com/ideacrew/enroll-fe2/issues/29
```
